project:
  type: website
  output-dir: _site

website:
  title: "Your Website Title"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: chapters/chapter1.qmd
        text: Chapter 1
      - href: chapters/chapter2.qmd
        text: Chapter 2

execute:
  enabled: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: right
    embed-resources: true